#!/usr/bin/env bash

# Ask for the administrator password upfront
# sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
# while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# TODO add desktop settings
# https://manpages.ubuntu.com/manpages/trusty/man1/gsettings.1.html
# e.g. mouse speed = gsettings get org.gnome.desktop.peripherals.mouse speed

###############################################################################
# General UI/UX                                                               #
###############################################################################

timedatectl set-local-rtc 1 --adjust-system-clock